// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Fábio Henrique de Lima Silva (fhl.bsb@gmail.com) All rights reserved.

//! Cross-validation tests: NAM-rs UPOLS vs C++ `dsp::ImpulseResponse`.
//!
//! Compares the UPOLS convolution engine against golden vectors generated by
//! the C++ reference binary (`tests/fixtures/render_ir.cpp`) using the same
//! deterministic PCG PRNG seeds and synthetic IR/signal formulas.
//!
//! The C++ `ImpulseResponse` applies a fixed gain reduction of
//! `10^(−0.9) ≈ 0.126` that NAM-rs does not.  All comparisons compensate
//! this gain before computing metrics.
//!
//! ESR threshold: **1e-3** (relaxed from the 1e-5 internal golden threshold)
//! due to FFT arithmetic differences between direct time-domain convolution
//! (C++) and frequency-domain UPOLS (Rust).  See `docs/cpp_parity_map.md` §13.

mod common;
use common::conv_helpers::process_full_signal;
use common::io_helpers::read_golden_bin;
use common::validation::report_dsp_fidelity;
use nam_rs::dsp::cabsim::conv::ConvEngine;

// ── Simple PCG PRNG (bit-identical to render_ir.cpp and cabsim_golden.rs) ──

struct SimplePcg {
    state: u64,
    inc: u64,
}

impl SimplePcg {
    fn new(seed: u64) -> Self {
        Self {
            state: seed.wrapping_add(1442695040888963407),
            inc: 1,
        }
    }

    fn next_f32(&mut self) -> f32 {
        let old_state = self.state;
        self.state = old_state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(self.inc | 1);
        let xorshifted = (((old_state >> 18) ^ old_state) >> 27) as u32;
        let rot = (old_state >> 59) as u32;
        let rotated = (xorshifted >> rot) | (xorshifted << ((-(rot as i32)) & 31));
        (rotated as f32) * 2.3283064e-10
    }

    fn next_f32_signed(&mut self) -> f32 {
        self.next_f32() * 2.0 - 1.0
    }
}

// ── Synthetic IR generator (same formula as render_ir.cpp) ──

fn synth_ir_deterministic(
    len: usize,
    freq: f32,
    decay: f32,
    sample_rate: u32,
    rng: &mut SimplePcg,
) -> Vec<f32> {
    let noise_level = 0.02;
    (0..len)
        .map(|n| {
            let t = n as f32 / sample_rate as f32;
            (std::f32::consts::TAU * freq * t).sin() * (-decay * t).exp()
                + noise_level * rng.next_f32_signed()
        })
        .collect()
}

// ── C++ gain compensation ──

/// C++ `ImpulseResponse` gain factor: `10^(−18×0.05) × 48000 / mSampleRate`.
/// At 48 kHz this simplifies to `10^(−0.9) ≈ 0.1258925`.
const CPP_GAIN: f32 = 0.125_892_53;

/// Reciprocal: `10^0.9 ≈ 7.943282`.  Multiply C++ output by this to undo
/// the C++ gain reduction before comparison.
const CPP_GAIN_INV: f32 = 7.943_282;

// ── Cross-validation scenario ──

struct CppScenario {
    label: &'static str,
    seed: u64,
    ir_len: usize,
    sig_len: usize,
    freq: f32,
    decay: f32,
    bin: &'static str,
    block_size: usize,
}

// ── Cross-validation helper ──

fn compare_golden_cpp(scenario: &CppScenario) {
    let project_root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let bin_path = project_root.join(scenario.bin);

    let (input, cpp_output) = read_golden_bin(&bin_path).expect("Failed to read C++ golden binary");

    assert_eq!(
        input.len(),
        scenario.sig_len,
        "[{label}] golden input length mismatch: expected {sig_len}, got {}",
        input.len(),
        label = scenario.label,
        sig_len = scenario.sig_len,
    );
    assert_eq!(
        cpp_output.len(),
        scenario.sig_len,
        "[{label}] golden output length mismatch: expected {sig_len}, got {}",
        cpp_output.len(),
        label = scenario.label,
        sig_len = scenario.sig_len,
    );

    let mut rng = SimplePcg::new(scenario.seed);
    let ir = synth_ir_deterministic(
        scenario.ir_len,
        scenario.freq,
        scenario.decay,
        48000,
        &mut rng,
    );

    let mut engine = ConvEngine::new(&ir, scenario.block_size);
    let upols_output = process_full_signal(&mut engine, &input);

    assert!(
        upols_output.len() >= scenario.sig_len,
        "[{label}] UPOLS output too short: {} < {sig_len}",
        upols_output.len(),
        label = scenario.label,
        sig_len = scenario.sig_len,
    );

    let upols_slice = &upols_output[..scenario.sig_len];

    let cpp_compensated: Vec<f32> = cpp_output.iter().map(|x| x * CPP_GAIN_INV).collect();

    eprintln!();
    eprintln!("[C++ × NAM-rs — {label}]", label = scenario.label);
    eprintln!("  C++ gain        = {CPP_GAIN:.6}  (compensation ×{CPP_GAIN_INV:.6})");
    eprintln!(
        "  IR length       = {ir_len}  |  signal = {sig_len}  |  block = {block_size}",
        ir_len = scenario.ir_len,
        sig_len = scenario.sig_len,
        block_size = scenario.block_size,
    );
    eprintln!(
        "  UPOLS out       = {} samples  |  golden = {} samples",
        upols_output.len(),
        scenario.sig_len,
    );

    report_dsp_fidelity(
        &cpp_compensated,
        upols_slice,
        5e-2,
        10.0,
        Some(1e-3),
        &format!("cabsim_{label}", label = scenario.label),
        48000,
    );
}

// ── Tests ──

#[test]
#[ignore = "cross-validation: requires C++ golden binaries (generate via golden_gen_build.sh [5b])"]
fn cross_validate_cabsim_cpp_short() {
    compare_golden_cpp(&CppScenario {
        label: "short",
        seed: 42,
        ir_len: 64,
        sig_len: 256,
        freq: 600.0,
        decay: 12.0,
        bin: "tests/fixtures/golden_cabsim_cpp_short.bin",
        block_size: 64,
    });
}

#[test]
#[ignore = "cross-validation: requires C++ golden binaries (generate via golden_gen_build.sh [5b])"]
fn cross_validate_cabsim_cpp_medium() {
    compare_golden_cpp(&CppScenario {
        label: "medium",
        seed: 137,
        ir_len: 512,
        sig_len: 1024,
        freq: 350.0,
        decay: 6.0,
        bin: "tests/fixtures/golden_cabsim_cpp_medium.bin",
        block_size: 64,
    });
}

#[test]
#[ignore = "cross-validation: requires C++ golden binaries (generate via golden_gen_build.sh [5b])"]
fn cross_validate_cabsim_cpp_long() {
    compare_golden_cpp(&CppScenario {
        label: "long",
        seed: 31337,
        ir_len: 8192,
        sig_len: 16384,
        freq: 200.0,
        decay: 2.0,
        bin: "tests/fixtures/golden_cabsim_cpp_long.bin",
        block_size: 64,
    });
}

/// NOT applicable — C++ `ImpulseResponse` hard-caps IR at 8192 samples
/// (`mMaxLength`).  The stress IR (32768 samples) exceeds this limit and
/// the C++ engine truncates it, making cross-validation meaningless.
/// The stress scenario is validated against direct convolution in
/// `tests/cabsim_golden.rs::test_cabsim_golden_stress` (ESR < 1e-5).
/// See `docs/cpp_parity_map.md` §13.1.3 divergence #5.
#[allow(dead_code)]
fn cross_validate_cabsim_cpp_stress_skipped() {
    // This test is intentionally omitted from the #[test] suite.
    // IR length 32768 > C++ mMaxLength (8192).
}
