// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Fábio Henrique de Lima Silva (fhl.bsb@gmail.com) All rights reserved.

//! EBU Tech 3341 LUFS compliance suite.
//!
//! Validates the BS.1770-4 integrated loudness implementation against
//! independently-generated test sequences with known LUFS target values.
//!
//! Sequences are generated by `tests/fixtures/generate_ebu_sequences.py`
//! using a Python implementation of the same K-weighting filter chain and
//! 2-pass gating algorithm. The Python LUFS serves as a cross-implementation
//! reference — not self-calibration.
//!
//! ## EBU Tech 3341 minimum compliance tolerances
//!
//! - Sine tones: ±0.1 LU (the standard tolerance for steady-state signals)
//! - Dynamic content: ±0.2 LU (wider tolerance per EBU spec)
//!
//! ## Test signals
//!
//! | File                             | Content              | Target LUFS |
//! |----------------------------------|----------------------|-------------|
//! | ebu_3341_1_sine_m23.wav          | 1 kHz sine, 5 s      | −23.000     |
//! | ebu_3341_7_sine_m33.wav          | 1 kHz sine, 5 s      | −33.000     |
//! | ebu_3341_sine_m18.wav            | 1 kHz sine, 5 s      | −18.000     |
//! | ebu_3341_dyn_alternating.wav     | alternating levels   | −23.272     |

use std::path::PathBuf;

// Reuse the WAV I/O used by cpp_parity tests
mod common;
use common::wav::read_wav_f32;
use nam_rs::testing::perceptual::{compute_integrated_lufs, compute_lra};

fn fixture_path(name: &str) -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("tests");
    p.push("fixtures");
    p.push(name);
    p
}

fn run_lufs_test(wav_name: &str, target_lufs: f64, tolerance: f64) -> f64 {
    let (samples, sr) = read_wav_f32(&fixture_path(wav_name)).expect("Failed to read EBU test WAV");
    let measured = compute_integrated_lufs(&samples, sr);
    let delta = (measured - target_lufs).abs();
    assert!(
        delta <= tolerance,
        "{wav_name}: LUFS={measured:.3}, target={target_lufs:.3}, delta={delta:.3} LU \
         (tolerance={tolerance:.1} LU)",
    );
    delta
}

// =============================================================================
// EBU Tech 3341 sine-tone compliance
// =============================================================================

/// **EBU Signal 1**: 1 kHz sine at the EBU R 128 reference level of −23.0 LUFS.
///
/// This is the canonical reference level for EBU loudness normalisation.
/// Tolerance: ±0.1 LU (EBU Tech 3341 minimum compliance).
#[test]
fn ebu_signal_1_sine_m23_lufs() {
    run_lufs_test("ebu_3341_1_sine_m23.wav", -23.000, 0.1);
}

/// **EBU Signal 7**: 1 kHz sine at −33.0 LUFS (10 dB below reference).
///
/// Validates linearity at low levels. Tolerance: ±0.1 LU.
#[test]
fn ebu_signal_7_sine_m33_lufs() {
    run_lufs_test("ebu_3341_7_sine_m33.wav", -33.000, 0.1);
}

/// **1 kHz sine at −18.0 LUFS** — common test level for dynamic content.
///
/// Validates linearity at higher levels. Tolerance: ±0.1 LU.
#[test]
fn ebu_sine_m18_lufs() {
    run_lufs_test("ebu_3341_sine_m18.wav", -18.000, 0.1);
}

// =============================================================================
// EBU Tech 3341 dynamic content compliance
// =============================================================================

/// **Dynamic signal**: alternating −20 / −46 dBFS 1 kHz sine.
///
/// Exercises the 2-pass gating algorithm: the quiet section is gated out
/// by the relative gate, leaving the integrated measurement dominated by
/// the loud section.
///
/// Tolerance: ±0.2 LU (wider for dynamic content per EBU spec).
#[test]
fn ebu_dyn_alternating_lufs() {
    run_lufs_test("ebu_3341_dyn_alternating.wav", -23.272, 0.2);
}

// =============================================================================
// Additional compliance: LRA on dynamic signal
// =============================================================================

/// Validates that LRA is measurable (> 0) on the dynamic signal
/// (alternating loud/quiet produces non-zero loudness range).
#[test]
fn ebu_dyn_alternating_lra() {
    let (samples, sr) = read_wav_f32(&fixture_path("ebu_3341_dyn_alternating.wav"))
        .expect("Failed to read EBU dynamic WAV");
    let lra = compute_lra(&samples, sr);
    // With 5 s (1 block of 3 s visible) the LRA may be 0 because we need ≥ 2 blocks
    // after gating. This test verifies the function doesn't panic and returns
    // a valid value (≥ 0).
    assert!(lra >= 0.0, "LRA must be non-negative, got {lra}");
}

// =============================================================================
// Self-consistency: identical signals produce identical LUFS
// =============================================================================

#[test]
fn ebu_sine_lufs_idempotent() {
    let (samples, sr) =
        read_wav_f32(&fixture_path("ebu_3341_1_sine_m23.wav")).expect("Failed to read EBU WAV");
    let l1 = compute_integrated_lufs(&samples, sr);
    let l2 = compute_integrated_lufs(&samples, sr);
    assert!(
        (l1 - l2).abs() < 1e-12,
        "LUFS must be deterministic: {l1} vs {l2}"
    );
}

// =============================================================================
// LUFS level linearity: doubling amplitude adds ~6 LU
// =============================================================================

#[test]
fn ebu_lufs_3db_linearity() {
    // −23 LUFS sine has amplitude A; −18 LUFS sine has amplitude ~1.78×A.
    // The LUFS difference should be exactly 5.0 LU (−23 to −18).
    let (samples_m23, sr) =
        read_wav_f32(&fixture_path("ebu_3341_1_sine_m23.wav")).expect("Failed to read EBU WAV");
    let (samples_m18, _) =
        read_wav_f32(&fixture_path("ebu_3341_sine_m18.wav")).expect("Failed to read EBU WAV");
    let l23 = compute_integrated_lufs(&samples_m23, sr);
    let l18 = compute_integrated_lufs(&samples_m18, sr);
    let delta = (l18 - l23).abs();
    assert!(
        (delta - 5.0).abs() < 0.2,
        "LUFS linearity: expected ~5.0 LU difference, got {delta:.3} LU"
    );
}
