// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Fábio Henrique de Lima Silva (fhl.bsb@gmail.com) All rights reserved.

//! Property-Based Tests for critical mathematical intrinsics (AVX2 / AVX-512).
//!
//! # Goal
//! Sweeps millions of random boundary values over Hyperbolic Tangent and Sigmoid, ensuring:
//! 1. Absence of computational failures (NaN / Inf).
//! 2. Strict RMSE ceiling against the original `f32::tanh` for the neural layer.

use nam_rs::math::activations::sigmoid::simd_sigmoid_avx2;
use nam_rs::math::activations::tanh::simd_tanh_avx2;
use nam_rs::math::gemm::dot::{dot_product_avx2, dot_product_avx512};
use proptest::prelude::*;

use core::arch::x86_64::{_mm256_loadu_ps, _mm256_storeu_ps};

prop_compose! {
    /// Strategy: Generates an array of 8 floats within a wide spectral range.
    /// The range [-10.0, 10.0] is enough to cover both the linear zone
    /// and the extreme saturation zones of Tanh and Sigmoid, where polynomial
    /// approximation errors usually appear.
    fn avx2_input_array()(
        a in -10.0f32..10.0f32,
        b in -10.0f32..10.0f32,
        c in -10.0f32..10.0f32,
        d in -10.0f32..10.0f32,
        e in -10.0f32..10.0f32,
        f in -10.0f32..10.0f32,
        g in -10.0f32..10.0f32,
        h in -10.0f32..10.0f32,
    ) -> [f32; 8] {
        [a, b, c, d, e, f, g, h]
    }
}

prop_compose! {
    /// Strategy: Generates pairs of equal-length vectors to test Dot Product.
    /// The size ranges from 1 to 512 to ensure the code correctly handles
    /// vectors that are not exact multiples of the SIMD register size (trailing elements).
    fn vec_pair_strategy()(len in 1..=512usize)
                          (a in prop::collection::vec(-10.0f32..10.0f32, len..=len),
                           b in prop::collection::vec(-10.0f32..10.0f32, len..=len)) -> (Vec<f32>, Vec<f32>) {
        (a, b)
    }
}

proptest! {
        // Configuration to run 10,000 iterations (80,000 floats swept).
        #![proptest_config(ProptestConfig {
            failure_persistence: Some(Box::new(proptest::test_runner::FileFailurePersistence::Off)),
            .. ProptestConfig::with_cases(10_000)
        })]

        /// Validates the precision of the Hyperbolic Tangent approximation via AVX2.
        /// Uses Minimax/Padé approximations that prioritize throughput over 64-bit precision.
    #[test]
    fn prop_simd_tanh_avx2_rmse(input in avx2_input_array()) {
            // Unaligned load, safe for generic buffers
        let vector = unsafe { _mm256_loadu_ps(input.as_ptr()) };
        let result_vector = unsafe { simd_tanh_avx2(vector) };

        let mut result = [0.0f32; 8];
        unsafe { _mm256_storeu_ps(result.as_mut_ptr(), result_vector) };

        for i in 0..8 {
            let expected = input[i].tanh();
            let actual = result[i];
            let error = (expected - actual).abs();

                // Fundamental guarantee: no activation may produce invalid values
                assert!(actual.is_finite(), "NaN/Inf output generated by FastMath Tanh polynomial!");

                // Sanity boundary: proptest sweeps [-10, 10] (beyond the optimized [-8, 8] range).
                // At extreme tails |x| > 8, the degree-7 Minimax polynomial may have larger error
                // (though the clamp at ±15.0 mitigates this). For the [-8, 8] range, the T7.2 sweep
                // confirmed max_error < 2e-5 (much tighter threshold).
            assert!(
                error <= 5e-3,
                    "Tanh precision failure. Input: {}. Expected: {}, Actual: {}, Delta: {}",
                input[i],
                expected,
                actual,
                error
            );
        }
    }

        /// Validates the precision of the FastMath Sigmoid implementation optimized for AVX2.
        ///
        /// Uses proptest to sweep the spectral domain and ensure the logistic function
        /// approximation does not exhibit instabilities or gross errors that would
        /// affect gating gain (where sigmoid is common).
    #[test]
    #[ignore]
    fn prop_simd_sigmoid_avx2_rmse(input in avx2_input_array()) {
            // Load 8 floats (256-bit YMM register)
            let vector = unsafe { _mm256_loadu_ps(input.as_ptr()) };
            // Execute sigmoid via intrinsic activations kernels
        let result_vector = unsafe { simd_sigmoid_avx2(vector) };

        let mut result = [0.0f32; 8];
        unsafe { _mm256_storeu_ps(result.as_mut_ptr(), result_vector) };

            // Scalar reference (f32::exp-based sigmoid)
        let std_sigmoid = |val: f32| -> f32 { 1.0 / (1.0 + (-val).exp()) };

        for i in 0..8 {
            let expected = std_sigmoid(input[i]);
            let actual = result[i];
            let error = (expected - actual).abs();

                assert!(actual.is_finite(), "Sigmoid produced unwanted NaN/Inf!");

                // The 5e-3 threshold reflects the precision of the direct degree-17
                // minimax polynomial (E8.T01). Errors at this magnitude are
                // negligible for dynamics control and gating modulation.
            assert!(
                error <= 5e-3,
                    "FastMath Sigmoid validation failed at {}. Expected: {}, Actual: {}, Delta: {}",
                input[i],
                expected,
                actual,
                error
            );
        }
    }
        /// Validates the AVX2 dot product with f32 weights.
        /// Compares against a scalar `f64` implementation (Ground Truth).
    #[test]
    #[ignore]
    fn prop_dot_product_avx2_vs_scalar((vec_a, vec_b) in vec_pair_strategy()) {
        let simd_result = unsafe { dot_product_avx2(&vec_a, &vec_b) };

            // Ground Truth in f64 to prevent test accumulation error from masking code error
        let scalar_result: f64 = vec_a.iter().zip(vec_b.iter()).map(|(&x, &y)| (x as f64) * (y as f64)).sum();

            // L1 norm to scale tolerable error on large vectors
        let l1_norm: f64 = vec_a.iter().zip(vec_b.iter()).map(|(&x, &y)| ((x as f64) * (y as f64)).abs()).sum();

        let error = (simd_result as f64 - scalar_result).abs();

        let threshold = 1e-6 * l1_norm.max(1.0);

        assert!(
            error <= threshold,
                "AVX2 dot product diverged from scalar! SIMD: {}, Ground Truth (f64): {}, Error: {}",
            simd_result,
            scalar_result,
            error
        );
    }

        /// Validates the AVX-512 dot product (when available in hardware).
    #[test]
    #[ignore]
    fn prop_dot_product_avx512_vs_scalar((vec_a, vec_b) in vec_pair_strategy()) {
            // Mandatory runtime check to prevent SIGILL on older CPUs
        if std::is_x86_feature_detected!("avx512f") {
            let simd_result = unsafe { dot_product_avx512(&vec_a, &vec_b) };

            let scalar_result: f64 = vec_a.iter().zip(vec_b.iter()).map(|(&x, &y)| (x as f64) * (y as f64)).sum();

            let error = (simd_result as f64 - scalar_result).abs();
            let threshold = (1e-6 * scalar_result.abs()).max(1e-6);

            assert!(
                error <= threshold,
                    "AVX-512 dot product diverged! SIMD: {}, Ground Truth (f64): {}, Error: {}",
                simd_result,
                scalar_result,
                error
            );
        }
    }
}
