// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Fábio Henrique de Lima Silva (fhl.bsb@gmail.com) All rights reserved.

//  Golden tests for the Linear FFT partitioned convolution engine.
// 
//  Validates the zero-latency FFT hybrid convolution (`LinearFftState`) against
//  the direct time-domain FIR convolution mathematical oracle. The direct FIR
//  convolution is identical to the C++ `nam::Linear` reference implementation
//  in `NeuralAmpModelerCore/NAM/dsp.cpp:255-301`.
// 
//  ## Test strategy
// 
//  - **Mathematical oracle tests** (fast, always run): Load `.nam` models with
//    long receptive fields (320, 2048, 4096, 8192 taps) via the full loader
//    pipeline, process deterministic test signals, and validate against the
//    direct FIR convolution oracle. The FFT engine must produce outputs
//    identical to the C++ time-domain reference within f32 floating-point
//    tolerance (ESR < 1e-6, SNR > 60 dB).
// 
//  - **C++ golden vector cross-reference**: Compare
//    NAM-rs output against pre-rendered `.golden.bin` files generated by
//    the C++ `NeuralAmpModelerCore` render tool. Requires running
//    `./tests/fixtures/golden_gen_build.sh` with Linear FFT models included.
//    Tests skip gracefully if golden files are not present.
// 
//  ## Fixture models
// 
//  | File                               | RF    | Partitions | Partition size P |
//  |------------------------------------|-------|-----------|-------------------|
//  | `linear_fft_rf320.nam`             | 320   | 2         | 128               |
//  | `linear_fft_rf2048.nam`            | 2048  | 1         | 1024              |
//  | `linear_fft_rf4096.nam`            | 4096  | 1         | 2048              |
//  | `linear_fft_rf8192.nam`            | 8192  | 1         | 4096              |

use super::common;

use common::{
    GOLDEN_BLOCK_SIZE, GOLDEN_NUM_SAMPLES,
    io_helpers::{model_path, process_in_blocks},
    signals::generate_sine_440hz,
    validation::{report_dsp_fidelity, report_dsp_fidelity_no_lufs},
};
use nam_rs::loader::dispatcher::build_model;
use nam_rs::loader::nam_json::LinearImplementation;
use nam_rs::loader::nam_json::parse_nam_json;
use nam_rs::models::linear::LinearModel;
use nam_rs::models::{NamModel, StaticModel};
use std::fs;
use std::path::PathBuf;

// ══════════════════════════════════════════════════════════════════════════════
// Deterministic PRNG (compatible with linear_golden.rs)
// ══════════════════════════════════════════════════════════════════════════════

struct SimplePcg {
    state: u64,
    inc: u64,
}

impl SimplePcg {
    fn new(seed: u64) -> Self {
        Self {
            state: seed.wrapping_add(1442695040888963407),
            inc: 1,
        }
    }

    fn next_f32(&mut self) -> f32 {
        let old_state = self.state;
        self.state = old_state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(self.inc | 1);
        let xorshifted = (((old_state >> 18) ^ old_state) >> 27) as u32;
        let rot = (old_state >> 59) as u32;
        let rotated = (xorshifted >> rot) | (xorshifted << ((-(rot as i32)) & 31));
        (rotated as f32) * 2.3283064e-10
    }

    fn next_f32_signed(&mut self) -> f32 {
        self.next_f32() * 2.0 - 1.0
    }
}

// ══════════════════════════════════════════════════════════════════════════════
// Mathematical Oracle: Direct FIR Convolution (= C++ Linear DSP reference)
// ══════════════════════════════════════════════════════════════════════════════

fn linear_oracle(input: &[f32], weights_forward: &[f32], bias: f32) -> Vec<f32> {
    let r = weights_forward.len();
    if r == 0 {
        return vec![bias; input.len()];
    }
    let mut output = vec![0.0f32; input.len()];
    for n in 0..input.len() {
        let mut sum = 0.0f32;
        let max_k = n.min(r - 1);
        for k in 0..=max_k {
            sum += weights_forward[k] * input[n - k];
        }
        output[n] = bias + sum;
    }
    output
}

// ══════════════════════════════════════════════════════════════════════════════
// Signal synthesis
// ══════════════════════════════════════════════════════════════════════════════

fn synth_multi_freq_signal(len: usize, rng: &mut SimplePcg) -> Vec<f32> {
    (0..len)
        .map(|i| {
            let t = i as f32 / 48000.0;
            0.45 * (std::f32::consts::TAU * 110.0 * t).sin()
                + 0.30 * (std::f32::consts::TAU * 440.0 * t).sin()
                + 0.15 * (std::f32::consts::TAU * 880.0 * t).sin()
                + 0.03 * rng.next_f32_signed()
        })
        .collect()
}

// ══════════════════════════════════════════════════════════════════════════════
// Helper: run model + compare against oracle
// ══════════════════════════════════════════════════════════════════════════════

fn verify_against_oracle(label: &str, weights_forward: &[f32], bias: f32, input: &[f32]) {
    let reference = linear_oracle(input, weights_forward, bias);

    let mut model = StaticModel::Linear(Box::new(
        LinearModel::new(weights_forward.to_vec(), bias, LinearImplementation::Fft)
            .expect("Linear model creation"),
    ));
    model.prewarm(input.len());
    let mut output = vec![0.0f32; input.len()];
    model.process(input, &mut output);

    // Use ESR as primary gate (scale-invariant, robust for FFT precision).
    // LUFS plausibility gate is disabled — IR convolution with large weights
    // legitimately produces output above +10 LUFS (same pattern as cabsim goldens).
    report_dsp_fidelity_no_lufs(
        &reference,
        &output,
        1e-6,
        60.0,
        Some(1e-6),
        None,
        label,
        48000,
    );
}

// ══════════════════════════════════════════════════════════════════════════════
// Fast Integration Tests — Mathematical Oracle (always run)
// ══════════════════════════════════════════════════════════════════════════════

#[test]
fn test_fft_golden_rf2048_sine_short() {
    let input = generate_sine_440hz(GOLDEN_NUM_SAMPLES);
    let rng = &mut SimplePcg::new(42);
    let weights: Vec<f32> = (0..2048)
        .map(|i| {
            let x = i as f32 / 2048.0;
            (std::f32::consts::TAU * 3.0 * x).cos() * (-2.0 * x).exp() * 0.9
                + 0.005 * rng.next_f32_signed()
        })
        .collect();
    verify_against_oracle("Linear FFT RF=2048 sine", &weights, 0.1, &input);
}

#[test]
fn test_fft_golden_rf2048_multi_freq() {
    let rng = &mut SimplePcg::new(137);
    let weights: Vec<f32> = (0..2048)
        .map(|i| {
            let x = i as f32 / 2048.0;
            (std::f32::consts::TAU * 3.0 * x).cos() * (-2.0 * x).exp() * 0.9
                + 0.005 * rng.next_f32_signed()
        })
        .collect();
    let input = synth_multi_freq_signal(4096, &mut SimplePcg::new(99));
    verify_against_oracle("Linear FFT RF=2048 multi-freq", &weights, -0.05, &input);
}

#[test]
fn test_fft_golden_rf4096_multi_freq() {
    let rng = &mut SimplePcg::new(256);
    let weights: Vec<f32> = (0..4096)
        .map(|i| {
            let x = i as f32 / 4096.0;
            (std::f32::consts::TAU * 3.0 * x).cos() * (-2.0 * x).exp() * 0.9
                + 0.005 * rng.next_f32_signed()
        })
        .collect();
    let input = synth_multi_freq_signal(8192, &mut SimplePcg::new(77));
    verify_against_oracle("Linear FFT RF=4096 multi-freq", &weights, 0.02, &input);
}

#[test]
fn test_fft_golden_rf8192_sine() {
    let input = generate_sine_440hz(16384);
    let rng = &mut SimplePcg::new(31337);
    let weights: Vec<f32> = (0..8192)
        .map(|i| {
            let x = i as f32 / 8192.0;
            (std::f32::consts::TAU * 3.0 * x).cos() * (-2.0 * x).exp() * 0.9
                + 0.003 * rng.next_f32_signed()
        })
        .collect();
    verify_against_oracle("Linear FFT RF=8192 sine", &weights, -0.01, &input);
}

#[test]
fn test_fft_golden_rf320_boundary() {
    // Tests the threshold boundary: RF=320 > 256, FFT should be active.
    // Partition size: P = largest_power_of_two_le(320/2) = largest_power_of_two_le(160) = 128
    // num_partitions: ceil((320-128)/128) = ceil(192/128) = 2
    let rng = &mut SimplePcg::new(777);
    let weights: Vec<f32> = (0..320)
        .map(|i| {
            let x = i as f32 / 320.0;
            (std::f32::consts::TAU * 2.5 * x).cos() * (-1.5 * x).exp() * 0.8
                + 0.01 * rng.next_f32_signed()
        })
        .collect();
    let input = synth_multi_freq_signal(2048, &mut SimplePcg::new(123));
    verify_against_oracle("Linear FFT RF=320 boundary", &weights, 0.05, &input);
}

#[test]
fn test_fft_golden_rf4096_impulse_response() {
    // Impulse at t=0, then silence. FFT tail must reproduce the IR exactly.
    let rng = &mut SimplePcg::new(888);
    let weights: Vec<f32> = (0..4096)
        .map(|i| {
            let x = i as f32 / 4096.0;
            (std::f32::consts::TAU * 2.0 * x).cos() * (-x).exp() * 0.7
                + 0.01 * rng.next_f32_signed()
        })
        .collect();
    let mut input = vec![0.0f32; weights.len() + 512];
    input[0] = 1.0; // impulse
    verify_against_oracle("Linear FFT RF=4096 impulse", &weights, 0.0, &input);
}

#[test]
fn test_fft_bitwise_determinism_large() {
    // Two identically-configured FFT models must produce bit-identical output.
    let weights: Vec<f32> = (0..2048)
        .map(|i| (i as f32 * 0.005).sin() * (-i as f32 * 0.0005).exp())
        .collect();
    let bias = 0.1;
    let input = synth_multi_freq_signal(4096, &mut SimplePcg::new(42));

    let mut model1 = StaticModel::Linear(Box::new(
        LinearModel::new(weights.clone(), bias, LinearImplementation::Fft).unwrap(),
    ));
    let mut model2 = StaticModel::Linear(Box::new(
        LinearModel::new(weights, bias, LinearImplementation::Fft).unwrap(),
    ));

    model1.prewarm(input.len());
    model2.prewarm(input.len());

    let mut out1 = vec![0.0f32; input.len()];
    let mut out2 = vec![0.0f32; input.len()];
    model1.process(&input, &mut out1);
    model2.process(&input, &mut out2);

    assert_eq!(out1.len(), out2.len());
    for (i, (a, b)) in out1.iter().zip(out2.iter()).enumerate() {
        assert!(
            (a - b).abs() < 1e-10,
            "bitwise determinism failed at sample {i}: {a} vs {b}"
        );
    }
}

#[test]
fn test_fft_reset_reproduces() {
    // Reset must restore exact initial state — output must be reproducible.
    let weights: Vec<f32> = (0..2048)
        .map(|i| (i as f32 * 0.005).sin() * (-i as f32 * 0.0005).exp())
        .collect();
    let bias = 0.05;
    let input = synth_multi_freq_signal(4096, &mut SimplePcg::new(99));
    let reference = linear_oracle(&input, &weights, bias);

    let mut model = StaticModel::Linear(Box::new(
        LinearModel::new(weights, bias, LinearImplementation::Fft).unwrap(),
    ));
    model.prewarm(input.len());
    let mut out1 = vec![0.0f32; input.len()];
    model.process(&input, &mut out1);

    model.reset(48000, 8192).unwrap();
    model.prewarm(input.len());
    let mut out2 = vec![0.0f32; input.len()];
    model.process(&input, &mut out2);

    for (i, ((vr, o1), o2)) in reference
        .iter()
        .zip(out1.iter())
        .zip(out2.iter())
        .enumerate()
    {
        assert!(
            (o1 - o2).abs() < 1e-6,
            "reset-reproduce mismatch between runs at sample {i}: {o1:.8e} vs {o2:.8e}"
        );
        assert!(
            (o1 - vr).abs() < 1e-4,
            "reset-reproduce: out1 diverged from oracle at sample {i}: {o1:.8e} vs {vr:.8e}"
        );
    }
}

// ══════════════════════════════════════════════════════════════════════════════
// Loader Pipeline Integration Tests — load .nam files via full pipeline
// ══════════════════════════════════════════════════════════════════════════════

/// Loads a .nam model file through the full dispatcher pipeline, processes the
/// input, and validates against the direct FIR oracle.
fn verify_nam_file_against_oracle(nam_filename: &str, label: &str, input: &[f32]) {
    let nam_path = model_path(nam_filename);
    assert!(
        nam_path.exists(),
        "Fixture model {nam_filename} not found at {nam_path:?}"
    );

    let json_data =
        fs::read_to_string(&nam_path).unwrap_or_else(|_| panic!("Failed to read {nam_filename}"));
    let model_data =
        parse_nam_json(&json_data).unwrap_or_else(|_| panic!("Failed to parse {nam_filename}"));
    let mut model =
        build_model(&model_data).unwrap_or_else(|_| panic!("Dispatcher failed for {nam_filename}"));

    // Extract weights and bias from the model for oracle computation.
    // The dispatcher loads weights in forward-time order from JSON.
    let weights: Vec<f32> = model_data
        .weights
        .iter()
        .take(model_data.weights.len().saturating_sub(1))
        .copied()
        .collect();
    let bias = model_data.weights.last().copied().unwrap_or(0.0);

    let reference = linear_oracle(input, &weights, bias);

    model.prewarm(input.len());
    let mut output = vec![0.0f32; input.len()];
    process_in_blocks(&mut model, input, &mut output, GOLDEN_BLOCK_SIZE);

    report_dsp_fidelity_no_lufs(
        &reference,
        &output,
        1e-6,
        60.0,
        Some(1e-6),
        None,
        label,
        48000,
    );
}

#[test]
fn test_fft_fixture_rf320_loader_pipeline() {
    let input = generate_sine_440hz(2048);
    verify_nam_file_against_oracle(
        "linear_fft_rf320.nam",
        "FFT fixture RF=320 (loader pipeline)",
        &input,
    );
}

#[test]
fn test_fft_fixture_rf2048_loader_pipeline() {
    let input = synth_multi_freq_signal(4096, &mut SimplePcg::new(42));
    verify_nam_file_against_oracle(
        "linear_fft_rf2048.nam",
        "FFT fixture RF=2048 (loader pipeline)",
        &input,
    );
}

#[test]
fn test_fft_fixture_rf4096_loader_pipeline() {
    let input = synth_multi_freq_signal(8192, &mut SimplePcg::new(137));
    verify_nam_file_against_oracle(
        "linear_fft_rf4096.nam",
        "FFT fixture RF=4096 (loader pipeline)",
        &input,
    );
}

#[test]
fn test_fft_fixture_rf8192_loader_pipeline() {
    let input = generate_sine_440hz(16384);
    verify_nam_file_against_oracle(
        "linear_fft_rf8192.nam",
        "FFT fixture RF=8192 (loader pipeline)",
        &input,
    );
}

// ══════════════════════════════════════════════════════════════════════════════
// Cross-block boundary tests — ensure FFT tail computation is seamless
// ══════════════════════════════════════════════════════════════════════════════

#[test]
fn test_fft_seamless_block_boundary() {
    // Process exactly P samples, then verify the output for the next P samples.
    // The FFT tail must be seamless across block boundaries.
    let p = 256; // partition size for RF=512: P = 256
    let weights: Vec<f32> = (0..512)
        .map(|i| (i as f32 * 0.01).sin() * (-i as f32 * 0.002).exp())
        .collect();
    let bias = 0.0;

    let ref_input: Vec<f32> = (0..2048)
        .map(|i| (i as f32 * 0.05).sin() * 0.5 + (i as f32 * 0.13).cos() * 0.3)
        .collect();
    let reference = linear_oracle(&ref_input, &weights, bias);

    let mut model = StaticModel::Linear(Box::new(
        LinearModel::new(weights, bias, LinearImplementation::Fft).unwrap(),
    ));
    model.prewarm(ref_input.len());
    let mut output = vec![0.0f32; ref_input.len()];
    model.process(&ref_input, &mut output);

    // Check each sample, highlighting block boundaries
    let mut max_diff = 0.0f32;
    let mut max_diff_idx = 0;
    for (i, (r, o)) in reference.iter().zip(output.iter()).enumerate() {
        let diff = (o - r).abs();
        if diff > max_diff {
            max_diff = diff;
            max_diff_idx = i;
        }
        if i > 0 && i % p == 0 {
            assert!(
                diff < 1e-3,
                "block boundary mismatch at sample {i} (P={p}): diff={diff:.2e}, ref={r:.6e}, out={o:.6e}"
            );
        }
    }
    assert!(
        max_diff < 1e-3,
        "max sample diff {max_diff:.2e} at idx {max_diff_idx} exceeds tolerance"
    );
}

#[test]
fn test_fft_long_seamless_boundaries() {
    // Multi-block seamless test with RF=2048 (P=1024, 2 partitions).
    // Verifies that the FFT tail reads from the correct sample_counter position
    // across multiple block computations.
    let weights: Vec<f32> = (0..2048)
        .map(|i| {
            let x = i as f32 / 2048.0;
            (std::f32::consts::TAU * 2.0 * x).cos() * (-1.5 * x).exp() * 0.8
        })
        .collect();
    let bias = 0.02;

    let num_samples = 16384;
    let rng = &mut SimplePcg::new(12345);
    let input: Vec<f32> = (0..num_samples)
        .map(|_| rng.next_f32_signed() * 0.5)
        .collect();
    let reference = linear_oracle(&input, &weights, bias);

    let mut model = StaticModel::Linear(Box::new(
        LinearModel::new(weights, bias, LinearImplementation::Fft).unwrap(),
    ));
    model.prewarm(input.len());
    let mut output = vec![0.0f32; input.len()];
    model.process(&input, &mut output);

    let mut max_diff = 0.0f32;
    for (r, o) in reference.iter().zip(output.iter()) {
        let diff = (o - r).abs();
        if diff > max_diff {
            max_diff = diff;
        }
    }

    let sum_sq_err: f64 = reference
        .iter()
        .zip(output.iter())
        .map(|(r, o)| (*r as f64 - *o as f64).powi(2))
        .sum();
    let sum_sq_ref: f64 = reference.iter().map(|r| (*r as f64).powi(2)).sum();
    let esr = sum_sq_err / sum_sq_ref;

    println!("\n[Linear FFT block-boundary validation — RF=2048 P=1024 16 blocks]");
    println!("  ESR    = {esr:.4e}");
    println!("  MaxErr = {max_diff:.2e}");
    println!("  Samples = {num_samples} @ 48 kHz");

    assert!(
        esr < 1e-6,
        "seamless block boundary ESR={esr:.4e} exceeds threshold 1e-6"
    );
}

// ══════════════════════════════════════════════════════════════════════════════
// C++ Golden Vector Cross-Reference (heavy — requires pre-generated .bin files)
// ══════════════════════════════════════════════════════════════════════════════

/// Runs a golden `.bin` test for a Linear FFT model.
///
/// Requires the `.golden.bin` file to exist in `tests/fixtures/`. Gracefully
/// skips if the file is not present (goldens must be generated via
/// `./tests/fixtures/golden_gen_build.sh`).
fn run_fft_golden_bin_test(model_filename: &str, golden_filename: &str, label: &str) {
    let fixtures_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    let nam_path = model_path(model_filename);
    let golden_path = fixtures_dir.join(golden_filename);

    if !nam_path.exists() {
        eprintln!("SKIP: Model {model_filename} not found. Skipping golden bin test '{label}'.");
        return;
    }

    if !golden_path.exists() {
        eprintln!(
            "SKIP: Golden file {golden_filename} not found at {golden_path:?}.\n\
             Run './tests/fixtures/golden_gen_build.sh' to generate Linear FFT golden vectors."
        );
        return;
    }

    let (input, expected) = common::io_helpers::read_golden_bin(&golden_path)
        .unwrap_or_else(|| panic!("Failed to read {golden_filename}"));

    let json_data = fs::read_to_string(&nam_path).expect("Failed to read Linear FFT model JSON");
    let model_data = parse_nam_json(&json_data).expect("Failed to parse Linear FFT model JSON");
    let mut model = build_model(&model_data)
        .unwrap_or_else(|_| panic!("Dispatcher failed for {model_filename}"));

    model.prewarm(GOLDEN_NUM_SAMPLES);
    let mut output = vec![0.0f32; input.len()];
    process_in_blocks(&mut model, &input, &mut output, GOLDEN_BLOCK_SIZE);

    let (mse_limit, min_snr_db, max_esr, mrstft_max) =
        common::validation::topology_thresholds(&model_data, model_filename);
    report_dsp_fidelity(
        &expected, &output, mse_limit, min_snr_db, max_esr, mrstft_max, label, 48000,
    );
}

#[test]
fn test_golden_vectors_linear_fft_rf2048() {
    run_fft_golden_bin_test(
        "linear_fft_rf2048.nam",
        "golden_linear_fft_rf2048.bin",
        "Linear FFT RF=2048 (C++ golden)",
    );
}

#[test]
fn test_golden_vectors_linear_fft_rf4096() {
    run_fft_golden_bin_test(
        "linear_fft_rf4096.nam",
        "golden_linear_fft_rf4096.bin",
        "Linear FFT RF=4096 (C++ golden)",
    );
}

#[test]
fn test_golden_vectors_linear_fft_rf8192() {
    run_fft_golden_bin_test(
        "linear_fft_rf8192.nam",
        "golden_linear_fft_rf8192.bin",
        "Linear FFT RF=8192 (C++ golden)",
    );
}
