[package]
name = "nam-rs-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_json = "1.0"

[dependencies.nam-rs]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "fuzz_nam_json"
path = "fuzz_targets/fuzz_nam_json.rs"
test = false
doc = false

[[bin]]
name = "fuzz_namb"
path = "fuzz_targets/fuzz_namb.rs"
test = false
doc = false
