// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Fábio Henrique de Lima Silva (fhl.bsb@gmail.com) All rights reserved.

//! Test wrappers and parity tests for t3k-mushra primitives ported in `nam_rs::testing::mushra`.

pub use nam_rs::testing::mushra::*;

use std::fs;
use std::path::PathBuf;

/// Returns the path to the pre-computed Mulberry32 golden vector from TypeScript.
fn ts_golden_path() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("tests/fixtures/mushra_prng_golden.bin");
    p
}

/// Tests bit-parity of Mulberry32 Rust port against TypeScript golden vector.
///
/// The golden is generated by running the t3k-mushra demo once and capturing
/// the first 1024 `next_f32()` values. Format:
/// ```text
/// [u32 num_values LE] [f32 x N values LE]
/// ```
#[test]
fn test_mulberry32_parity_with_ts() {
    let path = ts_golden_path();
    if !path.exists() {
        eprintln!(
            "SKIP: test_mulberry32_parity_with_ts — golden file not found at {:?}",
            path
        );
        eprintln!("Generate it by running the t3k-mushra demo and capturing PRNG output.");
        return;
    }

    let data = fs::read(&path).expect("Failed to read TS golden");
    assert!(data.len() >= 4, "Golden file too small");

    let num_values = u32::from_le_bytes([data[0], data[1], data[2], data[3]]) as usize;
    let expected_size = 4 + num_values * 4;
    assert_eq!(
        data.len(),
        expected_size,
        "Golden size mismatch: got {} bytes, expected {expected_size}",
        data.len()
    );

    let expected: Vec<f32> = (0..num_values)
        .map(|i| {
            let off = 4 + i * 4;
            f32::from_le_bytes([data[off], data[off + 1], data[off + 2], data[off + 3]])
        })
        .collect();

    // The TypeScript demo initializes mulberry32 with fnv1a32("t3k-mushra-demo")
    let seed = fnv1a32(b"t3k-mushra-demo");
    let mut rng = Mulberry32::new(seed);

    // Verify first 1024 values
    let check_count = num_values.min(1024);
    let mut all_match = true;
    for (i, exp_val) in expected.iter().enumerate().take(check_count) {
        let got = rng.next_f32();
        if (got - exp_val).abs() > f32::EPSILON {
            eprintln!(
                "Mismatch at index {i}: expected {:?}, got {:?} (diff {:e})",
                exp_val,
                got,
                (got - exp_val).abs()
            );
            all_match = false;
            break;
        }
    }
    assert!(
        all_match,
        "Mulberry32 Rust port does not match TypeScript golden"
    );
    println!(
        "  test_mulberry32_parity_with_ts: {check_count}/{} values match ✓",
        expected.len()
    );
}
