// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Fábio Henrique de Lima Silva (fhl.bsb@gmail.com) All rights reserved.

//! Test wrappers and golden-vector parity tests for perceptual metrics
//! (ESR + MR-STFT) from `nam_rs::testing::perceptual`.

pub use nam_rs::testing::perceptual::*;

use std::fs;
use std::path::PathBuf;

/// Returns the path to the pre-computed MR-STFT golden vector from Python reference.
fn mr_stft_golden_path() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("tests/fixtures/mrstft_golden.bin");
    p
}

/// Tests parity of the MR-STFT Rust implementation against a Python-generated golden.
///
/// The golden is generated by `tests/fixtures/scripts/gen_mrstft_golden.py` which uses
/// weights `[0.1, 0.3, 0.5]` for window sizes `[256, 1024, 4096]`.
///
/// Format:
/// ```text
/// [f64 MR-STFT loss LE]  (8 bytes)
/// [u32 num_samples LE]   (4 bytes)
/// [f32×N reference samples LE]
/// [f32×N test samples LE]
/// ```
#[test]
fn test_mr_stft_parity_with_python() {
    let path = mr_stft_golden_path();
    if !path.exists() {
        eprintln!(
            "SKIP: test_mr_stft_parity_with_python — golden file not found at {:?}",
            path
        );
        eprintln!("Generate it by running: python tests/fixtures/scripts/gen_mrstft_golden.py");
        return;
    }

    let data = fs::read(&path).expect("Failed to read MR-STFT golden");

    let min_header = 8 + 4;
    assert!(
        data.len() >= min_header,
        "Golden file too small: {} bytes",
        data.len()
    );

    let expected_loss = f64::from_le_bytes([
        data[0], data[1], data[2], data[3], data[4], data[5], data[6], data[7],
    ]);

    let num_samples = u32::from_le_bytes([data[8], data[9], data[10], data[11]]) as usize;
    let expected_size = 12 + num_samples * 4 * 2;
    assert_eq!(
        data.len(),
        expected_size,
        "Golden size mismatch: got {} bytes, expected {expected_size}",
        data.len()
    );

    let ref_start = 12;
    let test_start = 12 + num_samples * 4;

    let reference: Vec<f32> = (0..num_samples)
        .map(|i| {
            let off = ref_start + i * 4;
            f32::from_le_bytes([data[off], data[off + 1], data[off + 2], data[off + 3]])
        })
        .collect();

    let test: Vec<f32> = (0..num_samples)
        .map(|i| {
            let off = test_start + i * 4;
            f32::from_le_bytes([data[off], data[off + 1], data[off + 2], data[off + 3]])
        })
        .collect();

    let computed = compute_mr_stft(&reference, &test);

    // Allow a small floating point tolerance between Rust and Python implementations
    let tolerance = 1e-6f64.max(expected_loss.abs() * 1e-4);
    let diff = (computed - expected_loss).abs();

    assert!(
        diff < tolerance,
        "MR-STFT mismatch: expected {expected_loss:.10e}, got {computed:.10e} (diff {diff:.2e}, tolerance {tolerance:.2e})",
    );

    println!(
        "  test_mr_stft_parity_with_python: expected {expected_loss:.6e}, got {computed:.6e} ✓"
    );
}
