// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Fábio Henrique de Lima Silva (fhl.bsb@gmail.com) All rights reserved.

//! WaveNet A2 model struct (`WaveNetA2<const CH: usize>`).
//!
//! Single layer-array of 23 dilated causal layers with skip-connection accumulator
//! and head rechannel convolution, matching the fast-path from `a2_fast.cpp`.
//!
//! ## Architecture
//!
//! 1. Input rechannel: `Conv1x1(1 → CH)` (bias, no activation)
//! 2. 23 layers: dilated conv → input-mixin → LeakyReLU → head_accum += out → layer1x1 → residual
//! 3. Head conv: `Conv1D(CH → 1, K=16, bias)` over head_accum ring → × head_scale
//!
//! Processing is chunked by `WAVENET_MAX_NUM_FRAMES` (64) with zero allocation on the hot-path.
//!
//! ## Cross-Validation and Golden Vectors
//!
//! A2 golden vectors are generated by the C++ render tool (`a2_fast.cpp` fast-path)
//! via `golden_gen_build.sh`, providing real cross-validation against the upstream
//! reference. See `docs/cpp_parity_map.md` §5 for the parity matrix.
//!
//! ### T7.8 — Root cause of initial A2 Rust×C++ divergence
//!
//! The initial Rust port diverged from C++ because `prewarm()` only zeroed buffers
//! while the C++ `A2FastModel::prewarm()` feeds `_prewarm_samples` frames of silence
//! through `process()`. Even with zero input, A2 layers produce non-zero activations
//! (conv bias + mixin × 0 + LeakyReLU), populating the head accumulator ring.
//! The Rust zero-fill vs C++ silent-process mismatch meant zero initial state in Rust
//! vs bias-driven steady state in C++ — causing frame-level divergence from the first
//! output sample. Fixed by making Rust `prewarm()` run `process()` with zeros for
//! `receptive_field_size` frames after the zero-fill, mirroring the C++ DSP::Reset
//! → prewarm() flow exactly.
//!
//! ## Accepted divergences
//!
//! - Rechannel weights are stored as u16 (f16/bf16) and dequantized at runtime.
//!   C++ uses native f32. The quantization error (< 1e-3 relative) is below the
//!   output SNR tolerance for A2 models.

use super::head::A2HeadConv;
use super::layer::A2Layer;
use super::params::{A2_DILATIONS, A2_HEAD_KERNEL_SIZE, A2_KERNEL_SIZES, A2_NUM_LAYERS};
use crate::dsp::mirror_buf::MirroredBuffer;
use crate::math::common::AlignedVec;
use crate::math::common::half::f16_bits_to_f32;
use crate::models::wavenet::common::WAVENET_MAX_NUM_FRAMES;

/// Computes the receptive field size for the A2 architecture.
///
/// Sum of `(kernel_size - 1) * dilation` across all 23 layers,
/// plus `(head_kernel_size - 1)` for the head convolution lookback.
#[inline]
pub const fn a2_receptive_field() -> usize {
    let mut rf = 0usize;
    let mut i = 0;
    while i < A2_NUM_LAYERS {
        rf += (A2_KERNEL_SIZES[i] - 1) * A2_DILATIONS[i];
        i += 1;
    }
    rf + (A2_HEAD_KERNEL_SIZE - 1)
}

/// Complete WaveNet A2 Model.
///
/// `CH` = channel count (3 for Lite/Nano, 8 for Full/Standard).
///
/// ## Ring buffer architecture (T2.3)
///
/// Each layer's history is a power-of-2 `MirroredBuffer<f32>` that provides
/// branchless reads via virtual-memory mirroring. The `buffer_start` pointer
/// advances through the 2× virtual mapping; when it approaches the 2× boundary,
/// it rewinds by subtracting `ring_size`. Reads at `buffer_start - offset` are
/// always valid because the mirrored mapping maps `[S, 2S)` → `[0, S)`.
///
/// The head accumulator uses a plain `AlignedVec` with pow2 mask (`& ring_mask`)
/// for branchless ring access — no MirroredBuffer needed since the head reads
/// are already mask-based.
///
/// ## Source of truth
/// - `a2_fast.cpp`: class `A2FastModel` (members, process, prewarm, reset)
/// - `detail.h`: `LayerArray::Process` (per-layer sequence)
pub struct WaveNetA2<const CH: usize> {
    /// 23 A2 layers (one per layer index). Populated by `set_weights` (T1.6).
    pub layers: Vec<A2Layer>,

    /// Input rechannel weights: `Conv1x1(1 → CH)` (no bias), u16 quantized.
    pub rechannel_w: AlignedVec<u16>,

    /// Head convolution (K=16 over skip-connection accumulator, bias, head_scale).
    pub head_conv: Option<A2HeadConv>,

    /// Head accumulator ring buffer (skip-connection sum, column-major, pow2 size).
    pub head_accum: AlignedVec<f32>,

    /// Write position in `head_accum` (in columns, wraps via `head_ring_mask`).
    pub head_write_pos: usize,

    /// Ring mask for `head_accum` (pow2 ring, mask = capacity - 1).
    pub head_ring_mask: usize,

    /// Per-layer history buffers: one MirroredBuffer per layer (23 total).
    /// Each buffer provides 2× virtual mapping for branchless ring access (T2.3).
    pub layer_buffers: Vec<MirroredBuffer<f32>>,

    /// Per-layer ring sizes in elements (pow2 page-aligned). For rewind: `start -= ring_size`.
    pub layer_ring_sizes: Vec<usize>,

    /// Per-layer maximum dilation lookback = (kernel-1) * dilation.
    pub layer_lookbacks: Vec<usize>,

    /// Per-layer buffer starts (advanced with each written frame, rewound near 2× boundary).
    pub layer_buffer_starts: Vec<usize>,

    /// Inter-layer data buffer: `CH × max_buffer_size` f32, reused across layers.
    /// Each layer reads from it, then writes its l1x1 residual back (in-place update).
    pub layer_in: AlignedVec<f32>,

    /// Total receptive field: sum of `(kernel-1)*dilation` + head kernel - 1.
    pub receptive_field_size: usize,

    /// Maximum frames per processing block (= `WAVENET_MAX_NUM_FRAMES`).
    pub max_buffer_size: usize,
}

impl<const CH: usize> WaveNetA2<CH> {
    /// Creates a new uninitialized WaveNet A2 model.
    ///
    /// Allocates ring buffers (MirroredBuffer per layer, pow2 head accumulator)
    /// sized for the architecture and computes the receptive field.
    /// Weight-bearing fields start empty and are populated by the weight loader (T1.6).
    pub fn new() -> Self {
        let rf = a2_receptive_field();
        let max_buf = WAVENET_MAX_NUM_FRAMES;

        let head_ring_size = (rf + max_buf + 1).next_power_of_two();
        let head_ring_mask = head_ring_size - 1;

        let mut layer_buffers = Vec::with_capacity(A2_NUM_LAYERS);
        let mut layer_ring_sizes = Vec::with_capacity(A2_NUM_LAYERS);
        let mut layer_lookbacks = Vec::with_capacity(A2_NUM_LAYERS);
        let mut layer_buffer_starts = Vec::with_capacity(A2_NUM_LAYERS);

        for i in 0..A2_NUM_LAYERS {
            let max_lookback = (A2_KERNEL_SIZES[i] - 1) * A2_DILATIONS[i];
            let cap = max_lookback + max_buf + 1;
            let mb = MirroredBuffer::<f32>::new(cap * CH)
                .expect("MirroredBuffer allocation for A2 layer ring failed");
            let ring_size = mb.size();
            layer_buffers.push(mb);
            layer_ring_sizes.push(ring_size);
            layer_lookbacks.push(max_lookback * CH);
            layer_buffer_starts.push(ring_size);
        }

        Self {
            layers: Vec::with_capacity(A2_NUM_LAYERS),
            rechannel_w: AlignedVec::new(CH, 0u16),
            head_conv: None,
            head_accum: AlignedVec::new(head_ring_size * CH, 0.0f32),
            head_write_pos: rf,
            head_ring_mask,
            layer_buffers,
            layer_ring_sizes,
            layer_lookbacks,
            layer_buffer_starts,
            layer_in: AlignedVec::new(CH * max_buf, 0.0f32),
            receptive_field_size: rf,
            max_buffer_size: max_buf,
        }
    }

    /// Returns the channel count.
    #[inline(always)]
    pub fn channels(&self) -> usize {
        CH
    }

    /// Returns the total receptive field size.
    #[inline(always)]
    pub fn receptive_field(&self) -> usize {
        self.receptive_field_size
    }

    /// Reallocates internal buffers to support the given maximum block size.
    ///
    /// Any block size is accepted: processing is internally chunked into
    /// sub-blocks of ≤ `WAVENET_MAX_NUM_FRAMES` (64) by [`process`], matching
    /// the kernel scratch buffer capacity (T2.1). Call this to inform the model
    /// of the negotiated CLAP/audio host block size so that internal ring
    /// buffers are sized correctly.
    ///
    /// If `max_buf` is smaller than or equal to the current capacity, this is a no-op.
    pub fn set_max_buffer_size(&mut self, max_buf: usize) {
        if max_buf <= self.max_buffer_size {
            return;
        }
        self.max_buffer_size = max_buf;
        let rf = self.receptive_field_size;

        self.layer_buffers.clear();
        self.layer_ring_sizes.clear();
        self.layer_lookbacks.clear();
        self.layer_buffer_starts.clear();

        for i in 0..A2_NUM_LAYERS {
            let max_lookback = (A2_KERNEL_SIZES[i] - 1) * A2_DILATIONS[i];
            let cap = max_lookback + max_buf + 1;
            let mb = MirroredBuffer::<f32>::new(cap * CH)
                .expect("MirroredBuffer reallocation for A2 layer ring failed");
            let ring_size = mb.size();
            self.layer_buffers.push(mb);
            self.layer_ring_sizes.push(ring_size);
            self.layer_lookbacks.push(max_lookback * CH);
            self.layer_buffer_starts.push(ring_size);
        }

        self.layer_in = AlignedVec::new(CH * max_buf, 0.0f32);

        let head_ring_size = (rf + max_buf + 1).next_power_of_two();
        self.head_ring_mask = head_ring_size - 1;
        self.head_accum = AlignedVec::new(head_ring_size * CH, 0.0f32);
        self.head_write_pos = rf;
    }

    /// Full forward pass through the A2 model.
    ///
    /// Processes `input` samples and writes to `output`.
    /// Requires layers to be populated via `set_weights` (T1.6).
    /// Outputs silence until weights are loaded.
    ///
    /// ## Ring buffer architecture (T2.3)
    ///
    /// Layer history uses `MirroredBuffer<f32>` with power-of-2 sizes.
    /// Writes go to unmasked positions in the 2× virtual mapping; reads are
    /// branchless because the mirror maps `[S, 2S)` → `[0, S)`. When
    /// `buffer_start` approaches the 2× boundary, it rewinds by subtracting
    /// `ring_size`. No `copy_within` / memmove on the hot path.
    ///
    /// Head accumulator uses a plain `AlignedVec` with pow2 mask (`& ring_mask`).
    /// A pre-write memmove preserves `K-1` tail samples when the ring is about
    /// to overflow, keeping the write-positions unmasked for vectorized stores.
    ///
    /// # Block Size Contract
    ///
    /// Any input size ≤ `max_buffer_size` is safe: processing is internally chunked
    /// into sub-blocks of ≤ `WAVENET_MAX_NUM_FRAMES` (64), matching the kernel scratch
    /// buffer capacity. Exceeding `max_buffer_size` causes silent truncation: only the
    /// first `max_buffer_size` frames are processed and the remaining are left as zeros.
    /// This matches the CLAP/audio host contract which guarantees
    /// `block_size <= max_block_size` negotiated at activation.
    pub fn process(&mut self, input: &[f32], output: &mut [f32]) {
        let total = input.len();
        if total == 0 {
            return;
        }

        output[..total].fill(0.0);

        if self.layers.is_empty() {
            self.head_write_pos += total;
            return;
        }

        debug_assert!(
            total <= self.max_buffer_size,
            "process: input ({total}) > max_buffer_size ({}) — host violated block-size contract",
            self.max_buffer_size
        );
        let nf_total = total.min(self.max_buffer_size);

        let mut pos = 0;
        while pos < nf_total {
            let nf = (nf_total - pos).min(WAVENET_MAX_NUM_FRAMES);
            let ch = CH;

            // ── Phase 0: rechannel pre-scaling: input × rechannel_w → layer_in ──
            for (f, x) in input[pos..pos + nf].iter().enumerate() {
                let base = f * ch;
                for c in 0..ch {
                    let rw = f16_bits_to_f32(self.rechannel_w[c]);
                    self.layer_in[base + c] = rw * x;
                }
            }

            let head_keep = A2_HEAD_KERNEL_SIZE - 1;
            let head_cap = self.head_ring_mask + 1;
            if self.head_write_pos + nf > head_cap {
                let keep_start = self.head_write_pos - head_keep;
                let keep_bytes = head_keep * ch;
                let src = keep_start * ch;
                self.head_accum.copy_within(src..src + keep_bytes, 0);
                self.head_write_pos = head_keep;
            }
            let head_wp = self.head_write_pos;

            for li in 0..A2_NUM_LAYERS {
                let is_first = li == 0;
                let is_last = li == A2_NUM_LAYERS - 1;
                let ring_size = self.layer_ring_sizes[li];
                let lookback = self.layer_lookbacks[li];
                let max_lookback_cols = lookback / ch;
                let bs = self.layer_buffer_starts[li];

                debug_assert!(bs >= lookback);
                debug_assert!(bs + nf * ch <= ring_size * 2);

                {
                    let buf = &mut self.layer_buffers[li];
                    buf[bs..bs + nf * ch].copy_from_slice(&self.layer_in[..nf * ch]);
                }

                if bs + nf * ch + self.max_buffer_size * ch > ring_size * 2 {
                    self.layer_buffer_starts[li] = bs + nf * ch - ring_size;
                } else {
                    self.layer_buffer_starts[li] = bs + nf * ch;
                }

                {
                    let history = &self.layer_buffers[li][bs - lookback..bs + nf * ch];
                    let layer = &self.layers[li];

                    if let Some(ch3_conv) = &layer.ch3_conv {
                        unsafe {
                            super::conv1d_ch3::layer_forward_ch3_block(
                                ch3_conv,
                                &layer.mixin_w,
                                &layer.l1x1_w,
                                &layer.l1x1_b,
                                history,
                                max_lookback_cols,
                                nf,
                                &input[pos..pos + nf],
                                &mut self.head_accum,
                                head_wp,
                                &mut self.layer_in,
                                is_first,
                                is_last,
                            );
                        }
                        continue;
                    }

                    if let Some(ch8_conv) = &layer.ch8_conv {
                        unsafe {
                            super::conv1d_ch8::layer_forward_ch8_block(
                                ch8_conv,
                                &layer.mixin_w,
                                &layer.l1x1_w,
                                &layer.l1x1_b,
                                history,
                                max_lookback_cols,
                                nf,
                                &input[pos..pos + nf],
                                &mut self.head_accum,
                                head_wp,
                                &mut self.layer_in,
                                is_first,
                                is_last,
                            );
                        }
                        continue;
                    }

                    // ── Scalar fallback: per-frame, per-layer ────────────────
                    for (f, x) in input[pos..pos + nf].iter().enumerate() {
                        let head_col = head_wp + f;
                        let lin_slice = &mut self.layer_in[f * ch..(f + 1) * ch];
                        let mut frame_z = [0.0f32; 8];
                        let z_slice = &mut frame_z[..ch];

                        let frame_idx = max_lookback_cols + f;

                        // ── Phase 1: dilated conv over receptive field ──────
                        unsafe {
                            layer
                                .conv
                                .process_single_frame(history, z_slice, frame_idx, None);
                        }

                        // ── Phase 2: input mixin (conditioning) ─────────────
                        let mixin: &[f32] = &layer.mixin_w;
                        for c in 0..ch {
                            z_slice[c] += mixin[c] * x;
                        }

                        // ── Phase 3: gated activation (leaky-ReLU, slope 0.01) ──
                        for z in z_slice.iter_mut().take(ch) {
                            if *z < 0.0 {
                                *z *= 0.01;
                            }
                        }

                        // ── Phase 4: head accumulation ─────────────────────
                        let head_off = head_col * ch;
                        if is_first {
                            self.head_accum[head_off..head_off + ch].copy_from_slice(z_slice);
                        } else {
                            for (c, z_val) in z_slice.iter().enumerate().take(ch) {
                                self.head_accum[head_off + c] += *z_val;
                            }
                        }

                        // ── Phase 5: 1×1 projection to next layer ──────────
                        if !is_last {
                            let l1x1: &[f32] = &layer.l1x1_w;
                            let l1x1_b: &[f32] = &layer.l1x1_b;
                            for c in 0..ch {
                                let mut sum = l1x1_b[c];
                                for u in 0..ch {
                                    sum += l1x1[u * ch + c] * z_slice[u];
                                }
                                lin_slice[c] += sum;
                            }
                        }
                    }
                }
            }

            self.head_write_pos = (head_wp + nf) & self.head_ring_mask;

            if let Some(ref head) = self.head_conv {
                head.process(
                    &self.head_accum,
                    self.head_write_pos,
                    self.head_ring_mask,
                    nf,
                    &mut output[pos..pos + nf],
                );
            }

            pos += nf;
        }
    }

    /// Pre-warms the model by filling the receptive field with silence.
    ///
    /// Mirrors `A2FastModel::prewarm()` in `a2_fast.cpp`: zeroes all buffers,
    /// then feeds `receptive_field_size` frames of zero input through `process()`
    /// so that layer biases populate the head accumulator ring — matching the
    /// C++ steady-state initial condition.
    #[cold]
    pub fn prewarm(&mut self) {
        for buf in &mut self.layer_buffers {
            let len = buf.size();
            buf[..len].fill(0.0);
        }
        for i in 0..A2_NUM_LAYERS {
            self.layer_buffer_starts[i] = self.layer_ring_sizes[i];
        }
        self.layer_in.fill(0.0);
        self.head_accum.fill(0.0);
        self.head_write_pos = self.receptive_field_size;

        if self.has_weights() {
            let prewarm_samples = self.receptive_field_size;
            let block = WAVENET_MAX_NUM_FRAMES;
            let zeros = vec![0.0f32; block];
            let mut discard = vec![0.0f32; block];
            let mut remaining = prewarm_samples;
            while remaining > 0 {
                let nf = remaining.min(block);
                self.process(&zeros[..nf], &mut discard[..nf]);
                remaining -= nf;
            }
        }
    }

    /// Resets internal state for a new sample rate and max buffer size.
    pub fn reset(&mut self, _sample_rate: u32, max_buffer_size: usize) {
        self.set_max_buffer_size(max_buffer_size);
        self.prewarm();
    }

    /// Returns whether weights have been loaded via `set_weights`.
    #[inline(always)]
    pub fn has_weights(&self) -> bool {
        !self.layers.is_empty()
    }
}

impl<const CH: usize> Default for WaveNetA2<CH> {
    fn default() -> Self {
        Self::new()
    }
}

mod set_weights;

#[cfg(test)]
#[path = "../model_test.rs"]
mod tests;
